version: "3.0"
services:
  node:
    container_name: node
    hostname: node
    build: dockerfiles/node
    volumes:
      - ./containers/node:/home/${USER}
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
    # user: ${UID}:${GID}
    working_dir: /home/${USER}
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      TZ: Asia/Tokyo
  db:
    image: "postgres:12"
    container_name: db
    hostname: db
    ports:
      - "54320:5432"
    volumes:
      - ./containers/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=js-fullstack
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=js-fullstack
    environment:
      TZ: Asia/Tokyo
